name: Deploy client-next

on:
  push:
    paths:
      - 'apps/client-next/**'
      - 'packages/ui/**'
      - 'packages/common/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2   #cloning the code

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
        ssh -t -i keyfile ubuntu@ec2-13-126-190-186.ap-south-1.compute.amazonaws.com "sudo bash /home/ubuntu/monorepo_demo/apps/client-next/deploy.sh"