name: CI/CD pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: action/checkout@v20   #cloning the code

      - name: SSH and deploy
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > keyfile
          chmod 600 keyfile
          mkdir -p ~/.ssh 
          cp known_hosts ~/.ssh/known_hosts
          ssh -t -i keyfile ubuntu#ec2-url "sudo bash ~/deploy.sh"
